### PR TITLE
Add Dynamic Media support to Core Image component

### PR DESCRIPTION
**Pull request by oufimtse**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | Yes
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

### CODE REVIEW

**Comment by msagolj** [comment]
@oborysyu is this PR a replacement for the previous one,  #1224 ? Also the PR should be based against development branch , see https://github.com/adobe/aem-core-wcm-components/blob/master/CONTRIBUTING.md#contributing-1.

**Comment by oufimtse** [comment]
@msagolj 
1. Yes, this #1261 is a replacement for #1224. I can close #1224 to reduce confusion.

2. Sorry about basing the PR against master instead of "development" branch. I have just re-based this PR so that it now points to "development" branch of the primary repo, hope it is fine.

**Comment by msagolj** [comment]
@oufimtse thank you. Just wanted to be sure before closing #1224 .

**Comment by msagolj** [comment]
If you apply `crop` or other edit values to a DM image, the image:
- If `DM feature` is enabled in image policy it simply ignores and renders correctly with DM settings
- If `DM feature` is disabled the image is broken

To reproduce:
- Turn off `DM feature` for image component
- Drop a DM image
- Apply crop in image edit

=> image output broken

same happens when:
- DM Feature is enabled
- You use edit to apply cropping
- Cropping gets ignored ,image renders correctly
- disable DM feature in Policy
- reload page

=> image broken

**Comment by oborysyu** [comment]
> If you apply `crop` or other edit values to a DM image, the image:
> 
> * If `DM feature` is enabled in image policy it simply ignores and renders correctly with DM settings
> * If `DM feature` is disabled the image is broken
> 
> To reproduce:
> 
> * Turn off `DM feature` for image component
> * Drop a DM image
> * Apply crop in image edit
> 
> => image output broken
> 
> same happens when:
> 
> * DM Feature is enabled
> * You use edit to apply cropping
> * Cropping gets ignored ,image renders correctly
> * disable DM feature in Policy
> * reload page
> 
> => image broken

This problem occurs with images which size is bigger when 3840px.
1) By default AdaptiveImageServlet use this value as maximum available size for image (https://github.com/adobe/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java#L98)
2) In the case image has bigger size it will not be rendered (to avoid running out of memory) - https://github.com/adobe/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java#L515
3) For big images we need to change default size from 3840 to bigger number. We can change it in "AEM Core WCM Components Adaptive Image Servlet Mapping Configuration" (http://localhost:4502/system/console/configMgr)

Thanks!

**Comment by msagolj** [comment]
@oborysyu indeed all the DM image samples I used for testing where bigger than this limit , my luck :) I verified again with a smaller image and it works as intended: with DM Feature enabled, cropping is ignored, with DM Feature is disabled cropping is applied. Thx for looking into this.

**Review by msagolj — APPROVED** [review]

**Pull request merged**
