### PR TITLE
Feature/942 deep linking accord tab

### LINKED ISSUE #942: Deep-linking capability on Accordion and Tabs components
## Feature Request

**Is your feature request related to a problem? Please describe.**
Content team should be able to anchor URLs to specific item/panel on these components.

**Describe the solution you'd like**
Each Item/Panel in accordion should have unique id.
Javascript should check the anchor and open the specific panel/item in the component and scroll the window to bring user on the anchored panel.

**Are there alternatives?**
No

**Documentation**
If you can, explain how users will be able to use this and possibly write out a version of the docs.
Maybe a screenshot or design?

### PR DESCRIPTION
**Pull request by rajramo61**
For issue references: Closes https://github.com/adobe/aem-core-wcm-components/issues/942
| ------------------------ | ---
| Fixed Issues?            | `Fixes #942`
| Patch: Bug Fix?          | No
| Minor: New Feature?      | Yes
| Major: Breaking Change?  | No
| Tests Added + Pass?      | No new tests added
| Documentation Provided   | Yes (code comments)
| Any Dependency Changes?  | No
| License                  | Apache License, Version 2.0

In previous PR, Accordion deep link capability was added. This PR contains the deep linking capability for Tabs component. Two files changed for this.
1) Tabs HTL file : ID for tab has been exchanged to add the resource name (node name) to make it unique and to support if the id is used in some campaign emails etc.
2) JS file modified to make the tab active with passed deep link id.

### CODE REVIEW

**Comment by jckautzmann** [comment]
Please see comment https://github.com/adobe/aem-core-wcm-components/pull/949#issuecomment-601652230 to see how this was solved as part of the PR for the data layer support.

**Comment by rajramo61** [comment]
> Please see comment [#949 (comment)](https://github.com/adobe/aem-core-wcm-components/pull/949#issuecomment-601652230) to see how this was solved as part of the PR for the data layer support.

@jckautzmann based on the reference you have provided, just trying to understand the change you are expecting. Here the ids for tab (li tag) and for tabpanel (div tag) for tab component.

Like: `tabs-<hash>-tab-item_<hash>` to `tabs-<hash>-item_<hash>-tab`
and
`tabs-<hash>-tabpanel-item_<hash>` to `tabs-<hash>-item_<hash>-tabpanel`
and the top tab id to change from `tabs-<hash>` to `tabs-<hash>-item-<hash>`
to support the DL changes?

Please clarify if my understanding is aligned with yours.

**Comment by jckautzmann** [comment]
@rajramo61 You can have a look at the new ID generation pattern for the tabs in the tabs.html file of the pull request files at:
https://github.com/adobe/aem-core-wcm-components/pull/949/files

**Comment by jckautzmann** [comment]
@rajramo61 @rajeevyadav2
As the implementation for item ID has changed, I created a new pull request #1011 that is based on the code provided through the two existing pull requests: #946 and #960.
Could you please review it?

**Comment by vladbailescu** [comment]
Closing, it was implemented in #1011

**Pull request closed without merging**
