### PR TITLE
Support for External Links in List component

### LINKED ISSUE #1047: [Navigation] [List] Allow External URLs
## Feature Request

**Is your feature request related to a problem? Please describe.**
A customer created an independent AEM site, but needed to link URLs to pages outside of the AEM instance as part of the footer link list and the header navigation. 

**Describe the solution you'd like**
Add the ability to include external links for the navigation component and the list component. 

**Are there alternatives?**
We used static HTML in place of custom components.

### PR DESCRIPTION
**Pull request by psm-aig**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #1047
| Patch: Bug Fix?          | No
| Minor: New Feature?      | Yes
| Major: Breaking Change?  | No
| Tests Added + Pass?      | Yes
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  | No
| License                  | Apache License, Version 2.0

New dropdown option will be available in the List dialog under the List Settings Tab -> Build List Using "List with External Links" which will support both external and internal links
Author will have multifield option where link and the title can be authored.
This new option is provided so that there is backward compatibility and there wont be any impact to the existing component.

### CODE REVIEW

**Comment by psm-aig** [comment]
Hi Team, 
Could you please provide an update w.r.t pull request.
Code coverage is more than 80% both at the individual file level and project level. 
Let me know in case of any modification

**Comment by psm-aig** [comment]
Hi Team,
Could you please review this pull request.
Thanks,
Prathik

**Comment by psm-aig** [comment]
Hi Team,

Could you please provide an update w.r.t pull request.
Code coverage is more than 80% both at the individual file level and project level.
Let me know in case of any modification or improve code coverage further more.

Please help us understand the reason why this PR is stuck at this stage.

Thanks,
Prathik

**Comment by satishkumarjadhav** [comment]
Hi Team,

Could you please review and let us know if there are any findings ?

Regards,

**Comment by vladbailescu** [comment]
This change should target List v3

**Comment by psm-aig** [comment]
Hi @jckautzmann - We see that pull request has been closed with unmerged commits - Could you please confirm if the committed changes are being considered in the 3.0.0 milestone List v3.

If not - please let us know the reason - we can work on the changes required and raise new PR

CC : @satishkumarjadhav 

Thanks,
Prathik
+91 9036073874

**Comment by jckautzmann** [comment]
@psm-aig Sorry, I had not seen your PR when working on the List v3 component. Could you please recreate a PR with your changes to the List v3 against the development branch?

**Pull request closed without merging**
