### PR TITLE
Navigation custom templates

### PR DESCRIPTION
**Pull request by niekraaijmakers**
Preliminary PR to see if it's something the community will receive.

Backwards compatible adjustments to navigation component, that makes the component greatly more flexible.
-Adds possibility to choose a custom template per page on a content policy or property level to override the item, itemContent and group templates.
-Adds a secondary tree if called with secondary selector - this is good to render complex flyouts etc where 2 trees are required. 
-Adds possibility to turn off marking an item active server side, you don't want this when caching the menu in HTTP cache. Adds data attributes instead so javascript can do this.

With these adjustments I can make a great showcase example for many clients. WDYT?

### CODE REVIEW

**Comment by richardhand** [comment]
@niekraaijmakers - thanks for the pull request! Have a quick look at the [Contributing Guidelines](https://github.com/adobe/aem-core-wcm-components/blob/development/CONTRIBUTING.md#contributing-code-), you will need to sign the [Adobe Contributor License Agreement](http://opensource.adobe.com/cla.html) for us to accept contributions.

I also suggest that you create GitHub issues for each of the three problems you are trying to solve here with some more information (screenshots if possible) explaining the value they bring so that we can provide a more fine-tuned feedback on each.

At first glance:
> Adds possibility to choose a custom template per page on a content policy or property level to override the item, itemContent and group templates.
This seems already available given the ability to override an HTL template in your proxy component.

> Adds a secondary tree if called with secondary selector - this is good to render complex flyouts etc where 2 trees are required.
As I understand, this is about adding a modifier `*--secondary` to the component. Have you considered using the [Style System](https://helpx.adobe.com/experience-manager/6-3/release-notes/style-system-fp.html) - it can apply a style class to the component wrapper div, and should allow you to render this alternative flyout navigation.

**Comment by vladbailescu** [comment]
Hi Niek, I'm not sure we understand exactly how you plan to use the secondary tree, it would be nice if you could add some details.

As for extending the models, I'm afraid with our rule of throwing an `UnsupportedOperationException`, we would need to create a new version. We have an ongoing discussion about keeping the current pattern though (see #503)

**Comment by niekraaijmakers** [comment]
Hey Vlad, sorry for the late reply. Being a consultant and all and currently no bench time whatsoever it's a bit tough to contribute.

Regarding the secondary tree, this is really because most more fancy menu structures these days require this, for comprehensive fly-outs . It makes it much more tough and maintainable for the front-end to code only based on 1 nested structure.
Especially if in the fly-out you have images, stages, trailers etc.

Ok if we have to create a new version, fine by me :)

**Comment by gabrielwalt** [comment]
@niekraaijmakers Do you have the intention to bring this further or are you currently too busy?
If you'd like to continue, we should probably open a corresponding issue where we create some simple specification that describes how we want this to work.

**Comment by gabrielwalt** [comment]
Closing this for now, please reopen if you want to continue to work on this topic, or if you have more information describing the intent or use-case.

**Pull request closed without merging**
