### PR TITLE
Removed role="button" from buttons.

### LINKED ISSUE #783: [Carousel] Button elements have role button
## Bug Report

**Current Behavior**
In the current markup of Carousel, button elements for rotation and slide control have additional attribute `role="button`. This is not required, since buttons get this role by default. This causes W3C validators to report warnings. That's nothing major, but might be worth addressing.

**Expected behavior/code**
No role="button on button elements

**Environment**
- Core Components version 2.6.0

### PR DESCRIPTION
**Pull request by dlemstra**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #783 
| Patch: Bug Fix?          | Yes
| Minor: New Feature?      | No
| Major: Breaking Change?  | No 
| Tests Added + Pass?      | No
| Documentation Provided   | No
| Any Dependency Changes?  | No
| License                  | Apache License, Version 2.0

### CODE REVIEW

**Comment by richardhand** [comment]
@jakublamprecht, @dlemstra - should we add `type=button` here? The default type for button is `submit` so I think that makes sense. A little out of scope of this issue, but we could perhaps add it while we're at it.

**Comment by dlemstra** [comment]
That does make sense to add. Will push a new commit to change this during my lunch break.

**Comment by richardhand** [comment]
Thanks @dlemstra! would be good to also have a quick check of `<button>`s used in other components.

**Comment by dlemstra** [comment]
Maybe that should be a new PR instead?

**Comment by richardhand** [comment]
@dlemstra - yep, I agree :)

**Pull request merged**
