### PR TITLE
[Library] General improvements

### PR DESCRIPTION
**Pull request by richardhand**
- review feedback - add component version to footer to each page
- based on a Core Components Version simple content fragment
- adds footer style

Examples:
screenshot 2019-02-26 at 19 59 39

screenshot 2019-02-26 at 19 47 38

### CODE REVIEW

**Comment by vladbailescu** [comment]
Could we add the footer via the template initial content? This way it won't be forgotten when creating new pages.

**Comment by richardhand** [comment]
@vladbailescu - added in 8a4b83e341ace5cf1357e5b44294a900a61aa529

**Comment by jckautzmann** [comment]
@richardhand The content fragment with the version should be part of the template structure (similar to the navigation): it should not be included on each page.

**Comment by richardhand** [comment]
@vladbailescu, @jckautzmann - created a footer area in the grid, removed the separator and content fragment from each page content and moved them to the template, using a text component instead of a content fragment.

**Pull request merged**
