### PR TITLE
Issue #212 [Title] Add support for anchors.

### LINKED ISSUE #212: [Title] Add ID to support anchors
It would be useful if titles would support anchors so you can link to a specific section of the page.

### PR DESCRIPTION
**Pull request by Shivanshmathur**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #212 
| Patch: Bug Fix?          |
| Minor: New Feature?      | Yes
| Major: Breaking Change?  |
| Tests Added + Pass?      | Yes
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

* User can manually enter an ID, spaces will automatically be removed.
* If ID field is empty, ID is generated as follows- *"Title's Text without spaces"* + *"-hash of component's unique path"*. I think this improves human readability.
* IDs are automatically updated if the component is moved to a new path.
* Didn't provide an option in Design Dialog to disable IDs (would do so if required).

### CODE REVIEW

**Comment by Shivanshmathur** [comment]
@richardhand @gabrielwalt This is the latest PR regarding issue #212.

**Comment by vladbailescu** [comment]
The PR looks good, only thing I would add is a Hobbes test for the id.

**Comment by richardhand** [comment]
Also looks good to me, @Shivanshmathur - will you have a chance to create the Hobbes test? Let me know if you need any help with it.

**Comment by Shivanshmathur** [comment]
@andreeadracea @vladbailescu @richardhand Done!

**Comment by gabrielwalt** [comment]
Closing this PR for now, because we'd rather want to add IDs on a more generic level, so that all components can benefit from it.

**Pull request closed without merging**
