### PR TITLE
SITES-4420 - [Page] Deprecate the Social Sharing component

### LINKED ISSUE #1918: [Page] Deprecate the Social Sharing component
We will deprecate the Social Sharing components as they don't seem used a lot.
They will be removed from the component library.

### PR DESCRIPTION
**Pull request by comanV**
Fixes #1918

### CODE REVIEW

**Comment by vladbailescu** [comment]
Shouldn't we also get rid of the social snippets in the Page (v3) component?
* https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/head.socialmedia.html
* https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/body.socialmedia_begin.html
* https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/body.socialmedia_end.html

**Comment by comanV** [comment]
> Shouldn't we also get rid of the social snippets in the Page (v3) component?
> 
> * https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/head.socialmedia.html
> * https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/body.socialmedia_begin.html
> * https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/body.socialmedia_end.html

Addressed in 99fbd00f5a60b6a98ffd2a7b39522f2a18dad294.

**Comment by jckautzmann** [comment]
Shouldn't we also add some logs to the Sling Model saying that the component is deprecated and should not be used in new projects?

**Review by bpauli — APPROVED** [review]

**Comment by comanV** [comment]
> Shouldn't we also add some logs to the Sling Model saying that the component is deprecated and should not be used in new projects?

Addressed in 4f5d874533bb31d9fbc485bf13090bac13979572.

**Review by jckautzmann — APPROVED** [review]

**Pull request merged**
