### PR TITLE
[Content Fragment] Order content fragments in asc of node - Fixes #698

### LINKED ISSUE #698: [Content Fragment List] Display in a specific order
## Bug Report

**Current Behavior**
When author configured content fragment list, Content fragments displayed in desc order of lastModified. Whenever the author updated the content fragments inside the content fragment list this display order will change. 

**Expected behavior/code**
When the author updates the content fragment inside the content fragment list. Display order should not change it should remain the same. 

**Environment**

**Possible Solution**
To provide a consistent display order, Have to add orderby predicate in query builder that generates content fragment in ContentFragmentListImpl.java.

### PR DESCRIPTION
**Pull request by surya057**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Content fragments will be displayed in a predictable order inside "Content fragment list" (first created will be displayed first) #698 
| Patch: Bug Fix?          | No
| Minor: New Feature?      | Yes
| Major: Breaking Change?  | No
| Tests Added + Pass?      | Yes
| Documentation Provided   | No
| Any Dependency Changes?  | Yes, surefire version upgraded to make the build successful 
| License                  | Apache License, Version 2.0

Current Behaviour: "Content fragments" inside "content fragment list" displayed based on "last modified- desc order" (recently updated content fragment will go to the bottom). which will keep on changing when the author updated the content.

To maintain the consistent JSON format, have added "orderby" predicate to query which is creating content fragments.

### CODE REVIEW

**Comment by surya057** [comment]
Hi Team,

We need this feature in our environment ASAP, so when these changes will go live. can someone please update this? 

Thank you,
Surya

**Comment by surya057** [comment]
Hi Team,

Is there a way to display content fragment list JSON order (/mypage.model.json) same as content fragments order displayed DAM (/assets.html/content/dam/myDAMAssets).

when I change the DAM asset order (/assets.html/content/dam/myDAMAssets), that should reflect in my JSON (/mypage.model.json).


Note:
DAM content fragment will display in node inserted order.
The first node will be displayed first, second will display second and so on.

In page, JSON will be displayed based on the last modified date. (As of now).

How to keep both orders in sync? Can someone please give some suggestion.

Thank you,
Surya

**Comment by bpauli** [comment]
@surya057 I created a new PR at https://github.com/adobe/aem-core-wcm-components/pull/739 where the sort order and order by property can be configured by the author. I think this is a more flexible solution and should also met you needs. Is it okay for you if I close this PR?

**Comment by surya057** [comment]
Hi @bpauli 
Thank you for the update, 

we can close this but is it possible to maintain the order of the JSON same as the order displayed in the DAM. 
Our authors are reordering content fragments in DAM and expecting the same order in JSON.

I was checking the solution for above, query builder sorting is based on properties. But content fragment displayed in DAM is just node order from top to bottom in crx/de.

I want to maintain the JSON sorting order same as DAM but it seems like it is not possible as per this forum discussion - https://forums.adobe.com/thread/2329728

Is there any workaround for this scenario, please advice.

Cheers.

**Pull request closed without merging**
